CREATE TABLE IF NOT EXISTS REGISTERED_USERS (
    ID UUID PRIMARY KEY,
    USERNAME  VARCHAR(30) UNIQUE NOT NULL,
    PASSWORD VARCHAR(20),
    DOB  VARCHAR(50),
    GENDER  VARCHAR(10),
    COUNTRY  VARCHAR(30),
    CITY  VARCHAR(30),
    EMAIL  VARCHAR(50),
    CREATED_AT TIMESTAMP,
    MEDICAL INT,
    NEGATIVE INT,
    POSITIVE INT,
    BLACKLIST JSON
);

CREATE TABLE IF NOT EXISTS USAGE_HISTORY (
    ID UUID PRIMARY KEY,
    USER_ID UUID NOT NULL,
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    STRAIN_ID INT,
    STRAIN_NAME VARCHAR,
    MEDICAL_RANK FLOAT,
    POSITIVE_RANK FLOAT,
    OVERALL_RANK INT,
    HEARTBEAT_HIGH INT,
    HEARTBEAT_LOW INT,
    HEARTBEAT_AVG INT,
    QUESTIONS_ANSWERS_DICTIONARY VARCHAR
);

CREATE TABLE IF NOT EXISTS ALL_STRAINS (
    ID UUID PRIMARY KEY,
    STRAIN_ID INT,
    STRAIN_NAME VARCHAR,
    RACE VARCHAR,
    DESCRIPTION VARCHAR,
    MEDICAL INT,
    POSITIVE INT,
    NEGATIVE INT,
    RANK FLOAT
);